import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { CheckCircle2, Plus, Search, XCircle } from 'lucide-react'
import { useAppStore } from '@/store/useAppStore'
import { bankAccounts } from '@/lib/banks'
import { resolveSystemAccountId } from '@/lib/engine'
import { bsToAd, makeBsKey, todayBs } from '@/lib/nepaliDate'
import { canTransitionCheque, chequeEntitlement, chequeRelativeState, filterPendingCheques, validateChequeInput } from '@/lib/cheques'
import { createCheque, createChequeBank, fetchChequeEvents, updateCheque, updateChequeBank } from '@/lib/supabase'
import { fmtMoney } from '@/lib/utils'
import { PageContent, PageHeader } from '@/components/layout/PageHeader'
import { SearchableSelect } from '@/components/inputs/SearchableSelect'
import { NepaliDateInput } from '@/components/inputs/NepaliDateInput'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card } from '@/components/ui/card'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import type { Cheque, ChequeBank, ChequeEvent, ChequeStatus } from '@/types'

const field = 'space-y-1'
const th = 'px-2 py-1.5 text-left text-[10px] uppercase tracking-wide text-muted-foreground'
const td = 'px-2 py-1.5 align-middle text-xs'
const INSTITUTION_TYPE_OPTIONS = ['Commercial Bank', 'Development Bank', 'Finance Company', 'Others'].map(label => ({ value: label, label }))

function useChequeAccess() {
  const modules = useAppStore(s => s.companyModules)
  const permissions = useAppStore(s => s.chequePermissions)
  const entitlement = modules.find(entry => entry.module?.key === 'cheque_management')
  return { ...chequeEntitlement(entitlement), permissions, entitlement }
}

function StatusBadge({ cheque }: { cheque: Cheque }) {
  const relative = chequeRelativeState(cheque)
  const tone = cheque.status === 'cleared' ? 'bg-emerald-50 text-emerald-700' : cheque.status === 'bounced' || relative.key === 'overdue' ? 'bg-red-50 text-red-700' : relative.key === 'today' ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-700'
  return <span className={`inline-flex rounded-full px-2 py-0.5 text-[10px] font-semibold ${tone}`}>{relative.label}</span>
}

function ChequeForm({ afterSave }: { afterSave?: () => void }) {
  const { company, parties, accounts, chequeBanks, cheques, refreshChequeData } = useAppStore()
  const access = useChequeAccess()
  const navigate = useNavigate()
  const [form, setForm] = useState({ cheque_number:'', bank_id:'', account_number:'', party_ledger_id:'', amount:'', issue_date_bs:todayBs(), due_date_bs:todayBs(), notes:'' })
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const settings = access.settings
  const banks = chequeBanks.filter(bank => bank.is_active)
  const selectedBank = banks.find(bank => bank.id === form.bank_id)
  const partyOptions = parties.filter(p => !p.is_archived).map(p => { const account=accounts.find(a=>a.id===p.account_id); return { value:p.account_id, label:p.name, searchText:`${p.name} ${p.phone||''} ${p.pan_vat||''} ${account?.group||''}`, group:account?.group } })
  const bankOptions = banks.map(bank => ({ value:bank.id, label:bank.bank_name, group:bank.institution_type||'Other', searchText:`${bank.bank_name} ${bank.institution_type||''} ${bank.branch_name||''}` }))
  const set = (key:string,value:string) => setForm(current => ({...current,[key]:value}))
  const reset = () => setForm({ cheque_number:'', bank_id:'', account_number:'', party_ledger_id:'', amount:'', issue_date_bs:todayBs(), due_date_bs:todayBs(), notes:'' })
  const save = async (again=false) => {
    if (!company) return
    const base = { cheque_number:form.cheque_number.trim(), bank_id:form.bank_id, account_number:form.account_number.trim(), party_ledger_id:form.party_ledger_id, amount:Number(form.amount), issue_date_bs:form.issue_date_bs, due_date_bs:form.due_date_bs }
    const invalid = validateChequeInput(base, !!settings?.allow_due_date_before_issue_date)
    if (invalid) return setError(invalid)
    if (cheques.some(c => c.bank_id===base.bank_id && c.account_number===base.account_number && c.cheque_number.toLowerCase()===base.cheque_number.toLowerCase())) return setError('A cheque with this bank, account, and cheque number already exists.')
    setSaving(true); setError('')
    try {
      const created = await createCheque({ ...base, company_id:company.id, issue_date:bsToAd(base.issue_date_bs), issue_date_bs_key:makeBsKey(base.issue_date_bs), due_date:bsToAd(base.due_date_bs), due_date_bs_key:makeBsKey(base.due_date_bs), notes:form.notes, linked_voucher_id:undefined, cleared_at:undefined, bounced_at:undefined, cancelled_at:undefined, status_reason:undefined, created_by:undefined, updated_by:undefined })
      await refreshChequeData()
      if (again) { reset(); afterSave?.() } else navigate(`/cheques/${created.id}`)
    } catch (cause) { setError(cause instanceof Error?cause.message:'Could not save cheque.') } finally { setSaving(false) }
  }
  return <Card className="mx-auto max-w-3xl p-3"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
    <div className={field}><Label>Cheque No.</Label><Input value={form.cheque_number} onChange={e=>set('cheque_number',e.target.value)} maxLength={50} autoFocus /></div>
    <div className={field}><Label>Cheque Issuing Bank</Label><SearchableSelect value={form.bank_id} onValueChange={value=>{const bank=banks.find(b=>b.id===value);setForm(current=>({...current,bank_id:value,account_number:bank?.account_number||''}))}} options={bankOptions} placeholder="Select party’s bank" searchPlaceholder="Search Nepal banks…" /></div>
    <div className={field}><Label>Party’s Cheque Account No.</Label><Input value={form.account_number} onChange={e=>set('account_number',e.target.value)} disabled={!settings?.allow_account_number_override && !!selectedBank?.account_number} /></div>
    <div className={field}><Label>Amount (Rs)</Label><Input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>set('amount',e.target.value)} /></div>
    <div className="space-y-1 sm:col-span-2"><Label>Received From</Label><SearchableSelect value={form.party_ledger_id} onValueChange={value=>set('party_ledger_id',value)} options={partyOptions} placeholder="Select party ledger" searchPlaceholder="Search parties and groups…" /></div>
    <div className={field}><Label>Issue Date (B.S.)</Label><NepaliDateInput value={form.issue_date_bs} onChange={value=>set('issue_date_bs',value)} /></div>
    <div className={field}><Label>Due Date (B.S.)</Label><NepaliDateInput value={form.due_date_bs} onChange={value=>set('due_date_bs',value)} min={settings?.allow_due_date_before_issue_date?undefined:form.issue_date_bs} /></div>
    <div className="space-y-1 sm:col-span-2 lg:col-span-4"><Label>Notes</Label><textarea className="min-h-16 w-full rounded-md border bg-white px-2 py-1.5 text-xs outline-none focus:ring-2 focus:ring-ring" value={form.notes} onChange={e=>set('notes',e.target.value)} /></div>
  </div>{error&&<p className="mt-2 text-xs text-destructive">{error}</p>}<div className="mt-3 flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={()=>navigate('/cheques/pending')}>Cancel</Button><Button variant="outline" disabled={saving} onClick={()=>save(true)}>Save & Create Another</Button><Button disabled={saving} onClick={()=>save(false)}>{saving?'Saving…':'Save Cheque'}</Button></div></Card>
}

export function CreateChequePage(){ return <><PageHeader title="Create Received Cheque" description="Record a cheque received from a party."/><PageContent><ChequeForm/></PageContent></> }

function StatusDialog({ cheque, status, open, onClose }: { cheque:Cheque|null; status:ChequeStatus; open:boolean; onClose:()=>void }) {
  const { company, rawAccounts, accountCategories, saveReceipt, refreshChequeData, cancelV } = useAppStore()
  const access=useChequeAccess(); const [reason,setReason]=useState(''); const [depositAccountId,setDepositAccountId]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
  const companyBanks=bankAccounts(rawAccounts,accountCategories,false)
  const cashAccountId=company?resolveSystemAccountId(rawAccounts,company.id,'cash'):''
  const cashAccount=rawAccounts.find(account=>account.id===cashAccountId)
  const settlementAccounts=[...(cashAccount&&!cashAccount.is_archived?[cashAccount]:[]),...companyBanks]
  const permission=status==='cleared'?'cheque.mark_cleared':status==='bounced'?'cheque.mark_bounced':'cheque.cancel'
  const confirm=async()=>{ if(!cheque||!company)return; if(!canTransitionCheque(cheque.status,status))return setError('This status transition is not allowed.'); if(!access.permissions.includes(permission))return setError('You do not have permission for this action.'); if((status==='bounced'&&access.settings?.require_status_reason_for_bounce||status==='cancelled'&&access.settings?.require_status_reason_for_cancel)&&!reason.trim())return setError('A reason is required.'); setBusy(true); let voucherId:string|undefined
    try { if(status==='cleared'){ if(!depositAccountId)throw new Error('Select the company bank ledger receiving this cheque.'); const voucher=await saveReceipt({allocations:[{account_id:cheque.party_ledger_id,amount:cheque.amount}],deposit_to_account_id:depositAccountId,narration:`Cheque ${cheque.cheque_number} cleared`,date_bs:todayBs()}); voucherId=voucher.id }
      await updateCheque(cheque.id,company.id,{status,status_reason:reason.trim()||undefined,linked_voucher_id:voucherId,cleared_to_account_id:status==='cleared'&&depositAccountId!==cashAccountId?depositAccountId:undefined,...(status==='cleared'?{cleared_at:new Date().toISOString()}:status==='bounced'?{bounced_at:new Date().toISOString()}:{cancelled_at:new Date().toISOString()})},cheque); await refreshChequeData(); onClose()
    } catch(cause) { if(voucherId) await cancelV(voucherId).catch(()=>undefined); const message=cause instanceof Error?cause.message:typeof cause==='object'&&cause&&'message' in cause?String(cause.message):'Could not update cheque.'; setError(message) } finally {setBusy(false)} }
  return <Dialog open={open} onOpenChange={value=>!value&&onClose()}><DialogContent><DialogHeader><DialogTitle>Mark cheque as {status}</DialogTitle></DialogHeader><p className="text-xs text-muted-foreground">{status==='cleared'?'Select whether the party cheque was deposited into a company bank or withdrawn as cash. A Receipt voucher will be created automatically.':'This action is recorded in the cheque audit history.'}</p>{status==='cleared'&&<div><Label>Received Into Cash / Bank Ledger</Label><SearchableSelect value={depositAccountId} onValueChange={setDepositAccountId} options={settlementAccounts.map(account=>({value:account.id,label:account.name,group:account.id===cashAccountId?'Cash-in-Hand':'Bank Accounts',searchText:`${account.name} ${account.group} ${account.id===cashAccountId?'cash cash-in-hand':''}`}))} placeholder="Select Cash ledger or company bank" searchPlaceholder="Search Cash or bank ledgers…"/></div>}<textarea className="min-h-20 rounded-md border bg-white p-2 text-xs" placeholder="Status note or reason" value={reason} onChange={e=>setReason(e.target.value)}/>{error&&<p className="text-xs text-destructive">{error}</p>}<DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy} onClick={confirm}>{busy?'Updating…':'Confirm'}</Button></DialogFooter></DialogContent></Dialog>
}

export function PendingChequesPage(){ const {cheques,chequeBanks,accounts}=useAppStore(); const access=useChequeAccess(); const navigate=useNavigate(); const [params,setParams]=useSearchParams(); const quick=params.get('filter')||'all'; const [query,setQuery]=useState(''); const [statusTarget,setStatusTarget]=useState<{cheque:Cheque;status:ChequeStatus}|null>(null)
  const partyParam=params.get('party'); const rows=useMemo(()=>filterPendingCheques(cheques,quick).filter(c=>!partyParam||c.party_ledger_id===partyParam).filter(c=>{const bank=chequeBanks.find(b=>b.id===c.bank_id);const party=accounts.find(a=>a.id===c.party_ledger_id);return `${c.cheque_number} ${bank?.bank_name||''} ${party?.name||''} ${c.account_number} ${c.notes||''}`.toLowerCase().includes(query.trim().toLowerCase())}),[cheques,quick,partyParam,query,chequeBanks,accounts]);
  return <><PageHeader title="Pending Cheques" description="Received cheques awaiting clearance." action={<Button onClick={()=>navigate('/cheques/new')}><Plus className="mr-1 h-3.5 w-3.5"/>Create Cheque</Button>}/><PageContent><div className="mb-2 flex flex-wrap gap-1">{[['all','Pending'],['today','Today'],['overdue','Overdue'],['7','Next 7 Days'],['30','Next 30 Days']].map(([key,label])=><Button key={key} size="sm" variant={quick===key?'default':'outline'} onClick={()=>setParams(key==='all'?{}:{filter:key})}>{label}</Button>)}<div className="relative ml-auto min-w-52"><Search aria-hidden="true" className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground"/><Input className="pl-8" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search cheque, bank, party…"/></div></div><Card className="overflow-x-auto"><table className="w-full min-w-[850px]"><thead className="border-b bg-muted/40"><tr><th className={th}>Cheque No.</th><th className={th}>Bank / Account</th><th className={th}>Party</th><th className={th}>Amount</th><th className={th}>Issue Date</th><th className={th}>Due Date</th><th className={th}>State</th><th className={th}>Actions</th></tr></thead><tbody>{rows.map(c=>{const bank=chequeBanks.find(b=>b.id===c.bank_id);const party=accounts.find(a=>a.id===c.party_ledger_id);return <tr key={c.id} onClick={()=>navigate(`/cheques/${c.id}`)} className="cursor-pointer border-b hover:bg-muted/30"><td className={`${td} font-semibold`}>{c.cheque_number}</td><td className={td}>{bank?.bank_name}<span className="block text-[10px] text-muted-foreground">{c.account_number}</span></td><td className={td}>{party?.name||'Unknown ledger'}</td><td className={`${td} num font-semibold`}>{fmtMoney(c.amount)}</td><td className={td}>{c.issue_date_bs}</td><td className={td}>{c.due_date_bs}</td><td className={td}><StatusBadge cheque={c}/></td><td className={td} onClick={e=>e.stopPropagation()}><div className="flex gap-1">{access.permissions.includes('cheque.mark_cleared')&&<Button size="sm" variant="outline" onClick={()=>setStatusTarget({cheque:c,status:'cleared'})}>Clear</Button>}{access.permissions.includes('cheque.mark_bounced')&&<Button size="sm" variant="outline" onClick={()=>setStatusTarget({cheque:c,status:'bounced'})}>Bounce</Button>}{access.permissions.includes('cheque.cancel')&&<Button size="sm" variant="ghost" onClick={()=>setStatusTarget({cheque:c,status:'cancelled'})}>Cancel</Button>}</div></td></tr>})}{!rows.length&&<tr><td colSpan={8} className="p-8 text-center text-xs text-muted-foreground">No matching pending cheques.</td></tr>}</tbody></table></Card></PageContent><StatusDialog cheque={statusTarget?.cheque||null} status={statusTarget?.status||'cleared'} open={!!statusTarget} onClose={()=>setStatusTarget(null)}/></> }

function BankDialog({bank,onClose}:{bank?:ChequeBank;onClose:()=>void}) {
  const {company,refreshChequeData}=useAppStore()
  const [value,setValue]=useState({bank_name:bank?.bank_name||'',branch_name:bank?.branch_name||'',institution_type:bank?.institution_type==='Other'?'Others':bank?.institution_type||'Commercial Bank',notes:bank?.notes||''})
  const [error,setError]=useState('')
  const save=async()=>{if(!company)return;if(!value.bank_name.trim())return setError('Enter the issuing bank name.');try{const updates={...value,bank_name:value.bank_name.trim(),ledger_account_id:null,account_number:'',source:bank?.source||'Custom'};if(bank)await updateChequeBank(bank.id,company.id,updates,bank);else await createChequeBank({...updates,company_id:company.id,is_active:true,account_holder_name:'',contact_number:'',created_by:undefined,updated_by:undefined});await refreshChequeData();onClose()}catch(e){setError(e instanceof Error?e.message:'Could not save bank.')}}
  return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>{bank?'Edit':'Add'} Issuing Bank</DialogTitle></DialogHeader><p className="text-xs text-muted-foreground">This is the bank printed on the party’s cheque, not your company bank ledger.</p><div className="grid gap-2 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Bank Name</Label><Input value={value.bank_name} onChange={e=>setValue(c=>({...c,bank_name:e.target.value}))} placeholder="Enter bank or financial institution" autoFocus/></div><div><Label>Branch (optional)</Label><Input value={value.branch_name} onChange={e=>setValue(c=>({...c,branch_name:e.target.value}))}/></div><div><Label>Institution Type</Label><SearchableSelect value={value.institution_type} onValueChange={institution_type=>setValue(c=>({...c,institution_type}))} options={INSTITUTION_TYPE_OPTIONS} placeholder="Select institution type" searchPlaceholder="Search institution types…"/></div><div className="sm:col-span-2"><Label>Notes</Label><Input value={value.notes} onChange={e=>setValue(c=>({...c,notes:e.target.value}))}/></div></div>{error&&<p className="text-xs text-destructive">{error}</p>}<DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={save}>Save Bank</Button></DialogFooter></DialogContent></Dialog>
}

export function ChequeBanksPage(){const {company,chequeBanks,cheques,refreshChequeData}=useAppStore();const [editing,setEditing]=useState<ChequeBank|null|undefined>(undefined);const [query,setQuery]=useState('');const rows=chequeBanks.filter(b=>`${b.bank_name} ${b.branch_name||''} ${b.institution_type||''}`.toLowerCase().includes(query.toLowerCase()));return <><PageHeader title="Issuing Banks" description="Banks and financial institutions appearing on cheques received from parties." action={<Button onClick={()=>setEditing(null)}><Plus className="mr-1 h-3.5 w-3.5"/>Add Other Bank</Button>}/><PageContent><Input className="mb-2 max-w-sm" placeholder="Search issuing banks…" value={query} onChange={e=>setQuery(e.target.value)}/><Card className="overflow-x-auto"><table className="w-full min-w-[650px]"><thead className="border-b bg-muted/40"><tr><th className={th}>Bank / Institution</th><th className={th}>Type</th><th className={th}>Pending Count</th><th className={th}>Pending Amount</th><th className={th}>Status</th><th className={th}>Actions</th></tr></thead><tbody>{rows.map(b=>{const pending=cheques.filter(c=>c.bank_id===b.id&&c.status==='pending');return <tr className="border-b" key={b.id}><td className={td}><strong>{b.bank_name}</strong><span className="block text-[10px] text-muted-foreground">{b.branch_name||b.source||'—'}</span></td><td className={td}>{b.institution_type||'Bank'}</td><td className={td}>{pending.length}</td><td className={`${td} num font-semibold`}>{fmtMoney(pending.reduce((s,c)=>s+c.amount,0))}</td><td className={td}>{b.is_active?'Active':'Inactive'}</td><td className={td}><Button size="sm" variant="outline" onClick={()=>setEditing(b)}>Edit</Button> <Button size="sm" variant="ghost" onClick={async()=>{if(!company)return;await updateChequeBank(b.id,company.id,{is_active:!b.is_active},b);await refreshChequeData()}}>{b.is_active?'Deactivate':'Activate'}</Button></td></tr>})}{!rows.length&&<tr><td colSpan={6} className="p-8 text-center text-xs text-muted-foreground">No issuing banks found. Re-run the cheque migration to seed the NRB list.</td></tr>}</tbody></table></Card></PageContent>{editing!==undefined&&<BankDialog bank={editing||undefined} onClose={()=>setEditing(undefined)}/>}</>}

export function ChequePartiesPage(){const {parties,accounts,cheques}=useAppStore();const navigate=useNavigate();const [query,setQuery]=useState('');const rows=parties.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).map(p=>{const related=cheques.filter(c=>c.party_ledger_id===p.account_id);const pending=related.filter(c=>c.status==='pending');const overdue=pending.filter(c=>chequeRelativeState(c).key==='overdue');return {p,account:accounts.find(a=>a.id===p.account_id),related,pending,overdue}}).sort((a,b)=>b.overdue.reduce((s,c)=>s+c.amount,0)-a.overdue.reduce((s,c)=>s+c.amount,0));return <><PageHeader title="Cheque Parties" description="Party ledger balances and received-cheque exposure are shown separately."/><PageContent><Input className="mb-2 max-w-sm" placeholder="Search parties…" value={query} onChange={e=>setQuery(e.target.value)}/><Card className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead className="border-b bg-muted/40"><tr><th className={th}>Party</th><th className={th}>Ledger Group</th><th className={th}>Ledger Balance</th><th className={th}>Pending Cheques</th><th className={th}>Overdue</th><th className={th}>Total Cheques</th></tr></thead><tbody>{rows.map(r=><tr key={r.p.id} className="cursor-pointer border-b hover:bg-muted/30" onClick={()=>navigate(`/cheques/pending?party=${encodeURIComponent(r.p.account_id)}`)}><td className={`${td} font-semibold`}>{r.p.name}</td><td className={td}>{r.account?.group}</td><td className={`${td} num`}>{fmtMoney(r.account?.balance||0)}</td><td className={`${td} num`}>{fmtMoney(r.pending.reduce((s,c)=>s+c.amount,0))}</td><td className={`${td} num text-destructive`}>{fmtMoney(r.overdue.reduce((s,c)=>s+c.amount,0))}</td><td className={td}>{r.related.length}</td></tr>)}</tbody></table></Card></PageContent></>}

export function ChequeDetailPage(){const {id}=useParams();const {company,cheques,chequeBanks,accounts}=useAppStore();const navigate=useNavigate();const cheque=cheques.find(c=>c.id===id);const [events,setEvents]=useState<ChequeEvent[]>([]);const [target,setTarget]=useState<ChequeStatus|null>(null);useEffect(()=>{if(company&&id)fetchChequeEvents(company.id,id).then(setEvents).catch(()=>setEvents([]))},[company,id]);if(!cheque)return <PageContent><p className="text-sm text-muted-foreground">Cheque not found.</p></PageContent>;const bank=chequeBanks.find(b=>b.id===cheque.bank_id);const party=accounts.find(a=>a.id===cheque.party_ledger_id);return <><PageHeader title={`Cheque ${cheque.cheque_number}`} description="Received cheque details and audit history." action={<Button variant="outline" onClick={()=>navigate('/cheques/pending')}>Back</Button>}/><PageContent><div className="grid gap-3 lg:grid-cols-[2fr_1fr]"><Card className="p-3"><div className="mb-3 flex items-center justify-between"><StatusBadge cheque={cheque}/><span className="num font-serif text-lg font-bold">{fmtMoney(cheque.amount)}</span></div><dl className="grid gap-2 text-xs sm:grid-cols-2">{[['Bank',bank?.bank_name],['Account Number',cheque.account_number],['Party',party?.name],['Party Ledger Balance',fmtMoney(party?.balance||0)],['Issue Date (B.S.)',cheque.issue_date_bs],['Due Date (B.S.)',cheque.due_date_bs],['Receipt Voucher',cheque.linked_voucher_id?'Created':'—'],['Notes',cheque.notes||'—']].map(([label,value])=><div key={label} className="border-b pb-1"><dt className="text-[10px] uppercase text-muted-foreground">{label}</dt><dd className="font-medium">{value}</dd></div>)}</dl>{cheque.status==='pending'&&<div className="mt-3 flex gap-2"><Button onClick={()=>setTarget('cleared')}><CheckCircle2 className="mr-1 h-3.5 w-3.5"/>Mark Cleared</Button><Button variant="outline" onClick={()=>setTarget('bounced')}><XCircle className="mr-1 h-3.5 w-3.5"/>Bounced</Button><Button variant="ghost" onClick={()=>setTarget('cancelled')}>Cancel</Button></div>}</Card><Card className="p-3"><h2 className="font-serif text-sm font-bold">Timeline</h2><div className="mt-2 space-y-2">{events.map(event=><div key={event.id} className="border-l-2 pl-2 text-xs"><p className="font-medium">{event.action.replaceAll('_',' ')}</p><p className="text-[10px] text-muted-foreground">{new Date(event.created_at).toLocaleString()}</p></div>)}{!events.length&&<p className="text-xs text-muted-foreground">No audit events found.</p>}</div></Card></div></PageContent><StatusDialog cheque={cheque} status={target||'cleared'} open={!!target} onClose={()=>setTarget(null)}/></>}
